@startuml

rectangle inputs {
component "nixos-hardware" as nixosHardware
component "nixos-generators" as nixosGenerators
}

rectangle cell {
component nixosModules
component homeModules
component hardwareProfiles
component nixosProfiles
component userProfiles
component arionProfiles
component homeProfiles
component nixosSuites
component homeSuites

component nixosConfigurations
component diskoConfigurations
component colmenaConfigurations
component installers
}


nixosHardware --> hardwareProfiles

nixosModules --> nixosProfiles
homeModules --> homeProfiles

nixosProfiles --> nixosSuites
userProfiles --> nixosSuites

hardwareProfiles --> nixosConfigurations
nixosProfiles --> nixosConfigurations
nixosSuites --> nixosConfigurations
homeProfiles --> nixosConfigurations
homeSuites --> nixosConfigurations

homeProfiles --> homeSuites

diskoConfigurations --> hardwareProfiles
arionProfiles --> nixosConfigurations
nixosConfigurations --> colmenaConfigurations
nixosConfigurations --> installers
nixosGenerators --> installers
 

@enduml
